Added healthcheck for users, update CI files to wait on services

diff --git a/.prow/client.yaml b/.prow/client.yaml
--- a/.prow/client.yaml
+++ b/.prow/client.yaml
@@ -16,6 +16,9 @@ presubmits:
 
               SONAR_PROJECT_KEY="Banka-2-Backend-Client"
               SONAR_PROJECT_NAME="Banka-2-Backend-Client"
+              SERVICES_NAMES="users main otc"
+              SERVICES_PORTS="8080 8081 8082"
+              THIS_SERVICE="client"
 
               start-docker.sh
 
@@ -31,17 +34,40 @@ presubmits:
               git reset --hard HEAD~1
               git checkout $branch
 
-              # Start all microservices
+              # Start all helper services
               docker network create --driver bridge bank2_net || true
               docker compose up -d mariadb
               docker compose up -d flyway
               docker compose up -d mongodb
               docker compose up -d redis
-              docker compose up -d users
-              docker compose up -d main
-              docker compose up -d otc
               
-              cd client
+              # Start microservices
+              services=$(echo ${SERVICES_NAMES} | xargs)
+              for service in $services
+              do
+                docker compose up -d --build ${service}  
+              done
+              
+              # Check all microservices available
+              max_attempts=10
+              ports=$(echo ${SERVICES_PORTS} | xargs)
+              for port in $ports
+              do
+                counter=0
+                until curl 127.0.0.1:${port}
+                do
+                  ((counter++))
+                  if [ $counter -ge $max_attempts ]
+                  then
+                    echo "Failed to ping 127.0.0.1:${port} after ${max_attempts}, exiting."
+                    exit 1
+                  fi
+                sleep 15
+                done
+              done
+              
+              # Environment ready, start test      
+              cd ${THIS_SERVICE}
 
               mvn clean verify sonar:sonar -Pcoverage \
                 -Dsonar.host.url=https://sonar.k8s.elab.rs \
@@ -73,23 +99,49 @@ postsubmits:
               set -euo pipefail
 
               SONAR_PROJECT_KEY="Banka-2-Backend-Client"
-              SONAR_PROJECT_NAME="Banka-2-Backend-client"
+              SONAR_PROJECT_NAME="Banka-2-Backend-Client"
+              SERVICES_NAMES="users main otc"
+              SERVICES_PORTS="8080 8081 8082"
+              THIS_SERVICE="client"
 
               start-docker.sh
 
-              # Start all microservices
+              # Start all helper services
               docker network create --driver bridge bank2_net || true
               docker compose up -d mariadb
               docker compose up -d flyway
               docker compose up -d mongodb
               docker compose up -d redis
-              docker compose up -d users
-              docker compose up -d main
-              docker compose up -d otc
+              
+              # Start microservices
+              services=$(echo ${SERVICES_NAMES} | xargs)
+              for service in $services
+              do
+                docker compose up -d --build ${service}  
+              done
+              
+              # Check all microservices available
+              max_attempts=10
+              ports=$(echo ${SERVICES_PORTS} | xargs)
+              for port in $ports
+              do
+                counter=0
+                until curl 127.0.0.1:${port}
+                do
+                  ((counter++))
+                  if [ $counter -ge $max_attempts ]
+                  then
+                    echo "Failed to ping 127.0.0.1:${port} after ${max_attempts}, exiting."
+                    exit 1
+                  fi
+                sleep 15
+                done
+              done
               
               ref=$(git rev-parse --abbrev-ref HEAD)
               
-              cd client
+              # Environment ready, start test      
+              cd ${THIS_SERVICE}
 
               mvn clean verify sonar:sonar -Pcoverage \
                 -Dsonar.host.url=https://sonar.k8s.elab.rs \
